const BASE_ROUTE_NAME = "/hotel-directories";

const BASE_ROUTE_BED_TYPE_NAME = `${BASE_ROUTE_NAME}/bed-types`;
const BASE_ROUTE_FOOD_TYPE_NAME = `${BASE_ROUTE_NAME}/food-types`;
const BASE_ROUTE_HOTEL_BRANDS_NAME = `${BASE_ROUTE_NAME}/hotel-brands`;

const hotelDirectories = {
	BASE: `${BASE_ROUTE_NAME}`,
	BASE_ROUTE_BED_TYPE_NAME,
	BASE_ROUTE_FOOD_TYPE_NAME,
	BASE_ROUTE_HOTEL_BRANDS_NAME,

	HOTELS_BRANDS_LIST: `${BASE_ROUTE_HOTEL_BRANDS_NAME}`,
	ADD_HOTEL_BRAND: `${BASE_ROUTE_HOTEL_BRANDS_NAME}/add-hotel-brand`,

	FOOD_TYPES_LIST: `${BASE_ROUTE_FOOD_TYPE_NAME}`,
	ADD_FOOD_TYPE: `${BASE_ROUTE_FOOD_TYPE_NAME}/add-food-type`,

	BAD_TYPES_LIST: `${BASE_ROUTE_BED_TYPE_NAME}`,
	ADD_BAD_TYPE: `${BASE_ROUTE_BED_TYPE_NAME}/add-bed-type`
};

export { hotelDirectories };
